### ISSUE TITLE
checklist of thing I would like to update

### ISSUE THREAD

**Issue by nancopeland** [nancopeland/old-portfolio-site#5]
- [x] create "About" page
- [x] add preliminary mockups to pub redesign page
- [x] add navigation between posts
- [x] are links to live projects clickable enough? 
- [ ] clean up jekyll files
- [x] fix ul/img issue in posts (see post on mobile)
